DEP-06: Immutable ETCD Backups
seshachalam-yv/etcd-druid pull request #1
Opened 2024-09-27 05:20 UTC by seshachalam-yv

**How to categorize this PR?**

/area TODO
/kind TODO

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2024-09-27 08:25 UTC, renormalize requested changes
Thanks for the very well written DEP @seshachalam-yv!
Just have one strong suggestion with regards to the terminology that is to be used. Thanks.

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +        - [Bucket Lock Mechanism](#bucket-lock-mechanism)
The term `Bucket Lock` is identical to the terminology used by one vendor - GCS. Perhaps we could come up with terminology which is vendor agnostic, since we plan on supporting multiple and each has their own terminology?

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +Ensuring the integrity and availability of ETCD backups is crucial for the stability and reliability of ETCD clusters. Making backups immutable protects against unintended or malicious modifications
The backups don't have anything to do with the stability of *currently running* etcd clusters. Only in cases of restoration do we care about the integrity of the backups. So perhaps we could emphasize that integrity matters whenever we need to restore?

Also do we need to specify "security posture"?
```suggestion
Ensuring the integrity and availability of ETCD backups is crucial for the ability to restore an ETCD cluster after it has irrecoverably gone down. Making backups immutable protects against unintended or malicious modifications post-creation, thereby enhancing the overall security posture.
```

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +The Bucket Lock feature configures a retention policy for a cloud storage bucket, governing how long objects in the bucket must be retained. It also allows for locking the bucket's retention policy,
The phrase `retention policy` might be confusing for someone who is familiar with the etcd repos in gardener. Case in point: https://github.com/gardener/etcd-backup-restore/pull/776#discussion_r1766294499.

In etcd-backup-restore, we already have a feature called `delta snapshot retention period` which might be confused with what is being expressed here - the duration for which a snapshot is immutable after upload.

Can we use something like `immutability period` as expressed here https://github.com/gardener/etcd-backup-restore/pull/776#discussion_r1766764425?

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +Operators are responsible for creating or updating buckets with these immutable settings. Etcd-druid will use the bucket details from `Etcd.Spec.Backup.Store.Container` to upload the ETCD snapshots.
Makes it more explicit? I don't mind if you don't want this extra sentence tbf.
```suggestion
Operators are responsible for creating or updating buckets with these immutable settings. Etcd-druid will continue to use the bucket details from `Etcd.Spec.Backup.Store.Container` to upload the ETCD snapshots. No additional configuration needs to be passed to etcd-druid.
```

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +Operators need to ensure that the ETCD backup configuration aligns with the immutability requirements. This includes setting appropriate retention periods.
Retention period here is slightly confusing again.

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +#### Handling of Hibernated Clusters
Since hibernation is a gardener/gardener concept, could we specify that in contexts where consumers/operators like gardener/gardener bring down their etcd clusters, the immutability guarantees might be at risk?

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +Approach 2 is feasible and can be achieved in two ways:
Can we also mention how approach 1 is not feasible at all since it would increase the immutability duration for **all** objects that are uploaded, including the ones that will be uploaded in the future to a longer duration; would significantly drive storage costs, so on?

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +- **Option A:** Wake up the ETCD cluster by increasing the replicas, take a snapshot, and then hibernate the ETCD by setting the replicas to zero.
This assumes the reader knows what happens in gardener/gardener's hibernation. Maybe we could instead say that the etcd cluster is brought up?

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +Option B is recommended since we are not disturbing the existing setup, and we can leverage the compaction job to take responsibility for this.
Just a suggestion, feel free to discard.
```suggestion
Option B is recommended since this is orthogonal to the existing setup, and we can leverage the compaction job to take responsibility for this.
```

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +Leverage the compaction job to take fresh snapshots periodically during hibernation, thus ensuring that new, immutable snapshots are regularly created and the integrity of the backup immutability is
```suggestion
Leverage the compaction job to take fresh snapshots periodically during hibernation, thus ensuring that new, immutable snapshots are regularly created and the integrity of the backups is maintained.
```

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +An alternative to implementing immutability via bucket-level retention is to use object-level retention policies. Object-level retention allows for more granular control over the retention periods of
Same suggestions about retention period v/s immutability period apply here specifically.

2024-09-27 08:25 UTC, renormalize commented on docs/proposals/06-immutable-etcd-backups.md
> +| Precedence between bucket-level and object-level retention periods | Maximum of bucket or object-level retention | Object-level retention has precedence | Object-level retention has precedence |
```suggestion
| Precedence between bucket-level and object-level retention periods | Maximum of bucket or object-level retention | Object-level retention has precedence | Maximum of bucket or object-level retention |
```

2024-10-01 11:42 UTC, seshachalam-yv commented
Closing this PR, since opening on upstream.

2024-10-01 11:42 UTC, closed without merging